site_name: Vultron CVD Protocol
site_url: 'https://certcc.github.io/Vultron/'
site_description: 'A protocol for coordinated vulnerability disclosure'
site_author: 'CERT Coordination Center'
copyright: >
  Copyright &copy; 2021-2024 Carnegie Mellon University.
  <br/><a href="#__consent">Change cookie settings</a>
nav:
  - Home: 'https://certcc.github.io/'
  - Vultron: 'index.md'
  - Learning Vultron: 'tutorials/index.md'
  - Understanding Vultron:
    - Introduction: 'topics/index.md'
    - Background:
        - Context: 'topics/background/index.md'
        - Interoperability: 'topics/background/interoperability.md'
        - Defining CVD Success: 'topics/background/cvd_success.md'
        - Documentation Overview: 'topics/background/overview.md'
        - Terms and Definitions: 'topics/background/terms.md'
        - Notation: 'topics/background/notation.md'
        - Versioning: 'topics/background/versioning.md'
    - Process Models:
      - Introduction: 'topics/process_models/index.md'
      - Report Management:
        - RM Process Model: 'topics/process_models/rm/index.md'
        - RM Participant Interactions: 'topics/process_models/rm/rm_interactions.md'
      - Embargo Management:
        - EM Process Model: 'topics/process_models/em/index.md'
        - Embargo Principles: 'topics/process_models/em/principles.md'
        - Default Embargoes: 'topics/process_models/em/defaults.md'
        - Negotiating Embargoes: 'topics/process_models/em/negotiating.md'
        - Adding Participants: 'topics/process_models/em/working_with_others.md'
        - Early Termination: 'topics/process_models/em/early_termination.md'
        - Case Splits and Merges: 'topics/process_models/em/split_merge.md'
      - Case State:
        - Vulnerability Lifecycle Events: 'topics/process_models/cs/events.md'
        - Introduction: 'topics/process_models/cs/index.md'
        - CS States: 'topics/process_models/cs/cs_model.md'
        - CS Transitions: 'topics/process_models/cs/transitions.md'
        - CS Process Model: 'topics/process_models/cs/model_definition.md'
      - Model Interactions:
        - Global vs Local Aspects: 'topics/process_models/model_interactions/index.md'
        - RM and EM Interactions: 'topics/process_models/model_interactions/rm_em.md'
        - RM, EM, CS Interactions: 'topics/process_models/model_interactions/rm_em_cs.md'
    - The Vultron Protocol:
        - Formal Protocol Summary: 'topics/formal_protocol/index.md'
        - Worked Example: 'topics/formal_protocol/worked_example.md'
    - Behavior Logic:
      - Behavior Tree Intro: 'topics/behavior_logic/index.md'
      - CVD Behaviors: 'topics/behavior_logic/cvd_bt.md'
      - Vulnerability Discovery Behavior: 'topics/behavior_logic/vuldisco_bt.md'
      - RM Behaviors:
        - RM BT Intro: 'topics/behavior_logic/rm_bt.md'
        - Validation: 'topics/behavior_logic/rm_validation_bt.md'
        - Prioritization: 'topics/behavior_logic/rm_prioritization_bt.md'
        - Closure: 'topics/behavior_logic/rm_closure_bt.md'
      - EM Behaviors:
        - EM BT Intro: 'topics/behavior_logic/em_bt.md'
        - Evaluate Proposed Embargo Behavior: 'topics/behavior_logic/em_eval_bt.md'
        - Propse Embargo Behavior: 'topics/behavior_logic/em_propose_bt.md'
        - Terminate Embargo Behavior: 'topics/behavior_logic/em_terminate_bt.md'
      - Do Work Behaviors:
        - Do Work Intro: 'topics/behavior_logic/do_work_bt.md'
        - Deployment: 'topics/behavior_logic/deployment_bt.md'
        - Fix Development: 'topics/behavior_logic/fix_dev_bt.md'
        - Reporting: 'topics/behavior_logic/reporting_bt.md'
        - Publication: 'topics/behavior_logic/publication_bt.md'
        - Monitoring Threats: 'topics/behavior_logic/monitor_threats_bt.md'
        - ID Assignment: 'topics/behavior_logic/id_assignment_bt.md'
        - Exploit Acquisition: 'topics/behavior_logic/acquire_exploit_bt.md'
      - Receive Messages Behaviors:
        - Receive Msg Intro: 'topics/behavior_logic/msg_intro_bt.md'
        - Receive RM Messages: 'topics/behavior_logic/msg_rm_bt.md'
        - Receive EM Messages: 'topics/behavior_logic/msg_em_bt.md'
        - Receive CS Messages: 'topics/behavior_logic/msg_cs_bt.md'
        - Receive Other Messages: 'topics/behavior_logic/msg_other_bt.md'
    - User Stories: 'topics/user_stories/index.md'
    - Measuring CVD:
        - Introduction: 'topics/measuring_cvd/index.md'
        - Possible Histories: 'topics/measuring_cvd/possible_histories.md'
        - Desirable Histories: 'topics/measuring_cvd/desirable_histories.md'
        - Random Walks: 'topics/measuring_cvd/random_walk.md'
        - Reasoning Over Histories: 'topics/measuring_cvd/reasoning_over_histories.md'
        - Discriminating Skill from Luck: 'topics/measuring_cvd/discriminating_skill_and_luck.md'
        - Observing Skill: 'topics/measuring_cvd/observing_skill.md'
        - Benchmarking CVD: 'topics/measuring_cvd/benchmarking.md'
        - Limitations and Future Work: 'topics/measuring_cvd/limitations_future_work.md'
    - Other Uses of Vultron:
        - Introduction: 'topics/other_uses/index.md'
        - Stakeholder Roles: 'topics/other_uses/roles_influence.md'
        - Defining Zero Days: 'topics/other_uses/zero_day.md'
        - Policy Formalization: 'topics/other_uses/policy_formalization.md'
        - Situation Awareness: 'topics/other_uses/situation_awareness.md'
        - VEP: 'topics/other_uses/vep.md'
        - CVD Action Rules: 'topics/other_uses/action_rules.md'
    - Related Work: 'topics/related_work/index.md'
    - Future Work:
        - Intro: 'topics/future_work/index.md'
        - CVD Directory: 'topics/future_work/cvd_directory.md'
        - Reward Functions: 'topics/future_work/reward_functions.md'
        - Ontology: 'topics/future_work/ontology.md'
        - Modeling and Simulation: 'topics/future_work/mod_sim.md'
  - Implementing Vultron:
      - Implementation Intro: 'howto/index.md'
      - A Case Object: 'howto/case_object.md'
      - Process Implementation: 'howto/process_implementation.md'
      - Vultron ActivityPub:
          - ActivityPub Intro: 'howto/activitypub/index.md'
          - Vultron AS Objects: 'howto/activitypub/objects.md'
          - Vultron AS Activities:
            - Intro: 'howto/activitypub/activities/index.md'
            - Reporting a Vulnerability: 'howto/activitypub/activities/report_vulnerability.md'
            - Initializing a Case: 'howto/activitypub/activities/initialize_case.md'
            - Managing a Case: 'howto/activitypub/activities/manage_case.md'
            - Transferring a Case: 'howto/activitypub/activities/transfer_ownership.md'
            - Suggest an Actor for a Case: 'howto/activitypub/activities/suggest_actor.md'
            - Invite an Actor to a Case: 'howto/activitypub/activities/invite_actor.md'
            - Initialize a Participant: 'howto/activitypub/activities/initialize_participant.md'
            - Manage Case Participants: 'howto/activitypub/activities/manage_participants.md'
            - Establish an Embargo: 'howto/activitypub/activities/establish_embargo.md'
            - Manage an Embargo: 'howto/activitypub/activities/manage_embargo.md'
            - Status Updates: 'howto/activitypub/activities/status_updates.md'
            - Acknowledging a Report: 'howto/activitypub/activities/acknowledge.md'
            - Error Handling: 'howto/activitypub/activities/error.md'
      - EM and iCalendar: 'howto/em_icalendar.md'
      - General Notes: 'howto/general_implementation.md'
  - Reference:
    - Reference Overview: 'reference/index.md'
    - Formal Protocol:
      - Introduction: 'reference/formal_protocol/index.md'
      - States: 'reference/formal_protocol/states.md'
      - Messages: 'reference/formal_protocol/messages.md'
      - Transitions: 'reference/formal_protocol/transitions.md'
      - Protocol Summary: 'reference/formal_protocol/conclusion.md'
    - Case States:
      - Intro: 'reference/case_states/index.md'
      - vfdpxa: 'reference/case_states/state_vfdpxa.md'
      - vfdpxA: 'reference/case_states/state_vfdpx_a_.md'
      - vfdpXa: 'reference/case_states/state_vfdp_x_a.md'
      - vfdpXA: 'reference/case_states/state_vfdp_x__a_.md'
      - vfdPxa: 'reference/case_states/state_vfd_p_xa.md'
      - vfdPxA: 'reference/case_states/state_vfd_p_x_a_.md'
      - vfdPXa: 'reference/case_states/state_vfd_p__x_a.md'
      - vfdPXA: 'reference/case_states/state_vfd_p__x__a_.md'
      - Vfdpxa: 'reference/case_states/state__v_fdpxa.md'
      - VfdpxA: 'reference/case_states/state__v_fdpx_a_.md'
      - VfdpXa: 'reference/case_states/state__v_fdp_x_a.md'
      - VfdpXA: 'reference/case_states/state__v_fdp_x__a_.md'
      - VfdPxa: 'reference/case_states/state__v_fd_p_xa.md'
      - VfdPxA: 'reference/case_states/state__v_fd_p_x_a_.md'
      - VfdPXa: 'reference/case_states/state__v_fd_p__x_a.md'
      - VfdPXA: 'reference/case_states/state__v_fd_p__x__a_.md'
      - VFdpxa: 'reference/case_states/state__v__f_dpxa.md'
      - VFdpxA: 'reference/case_states/state__v__f_dpx_a_.md'
      - VFdpXa: 'reference/case_states/state__v__f_dp_x_a.md'
      - VFdpXA: 'reference/case_states/state__v__f_dp_x__a_.md'
      - VFdPxa: 'reference/case_states/state__v__f_d_p_xa.md'
      - VFdPxA: 'reference/case_states/state__v__f_d_p_x_a_.md'
      - VFdPXa: 'reference/case_states/state__v__f_d_p__x_a.md'
      - VFdPXA: 'reference/case_states/state__v__f_d_p__x__a_.md'
      - VFDpxa: 'reference/case_states/state__v__f__d_pxa.md'
      - VFDpxA: 'reference/case_states/state__v__f__d_px_a_.md'
      - VFDpXa: 'reference/case_states/state__v__f__d_p_x_a.md'
      - VFDpXA: 'reference/case_states/state__v__f__d_p_x__a_.md'
      - VFDPxa: 'reference/case_states/state__v__f__d__p_xa.md'
      - VFDPxA: 'reference/case_states/state__v__f__d__p_x_a_.md'
      - VFDPXa: 'reference/case_states/state__v__f__d__p__x_a.md'
      - VFDPXA: 'reference/case_states/state__v__f__d__p__x__a_.md'
    - Code:
        - vultron: 'reference/code/index.md'
        - case_states: 'reference/code/case_states.md'
        - Behavior Trees:
          - BT: 'reference/code/bt/behavior_trees.md'
          - Base: 'reference/code/bt//bt_base.md'
          - Nodes: 'reference/code/bt/bt_base_nodes.md'
          - Pacman Demo: 'reference/code/bt/pacman_demo.md'
          - Robot Demo: 'reference/code/bt/robot_demo.md'
          - Vultrabot Demo: 'reference/code/bt/vultrabot_demo.md'
          - Vultron Case State BT: 'reference/code/bt/case_states.md'
        - ActivityStreams Vocabulary:
          - Vocabulary: 'reference/code/as_vocab/index.md'
          - Base Package: 'reference/code/as_vocab/as_base.md'
          - Base Objects: 'reference/code/as_vocab/as_objects.md'
          - Base Links: 'reference/code/as_vocab/as_links.md'
          - Base Activities: 'reference/code/as_vocab/as_activities.md'
          - Vultron Extensions: 'reference/code/as_vocab/vultron.md'
          - Vultron Objects: 'reference/code/as_vocab/v_objects.md'
          - Vultron Activities: 'reference/code/as_vocab/v_activities.md'
    - Ontology:
      - Intro: 'reference/ontology/index.md'
      - Vultron_AS: 'reference/ontology/vultron_as.md'
      - Vultron_Protocol: 'reference/ontology/vultron_protocol.md'
      - Vultron_Process: 'reference/ontology/vultron_process.md'
      - DFA: 'reference/ontology/dfa.md'
      - RFC 2119: 'reference/ontology/rfc2119.md'
    - ISO Crosswalk:
      - Introduction: 'reference/iso_crosswalks/index.md'
      - ISO 30111: 'reference/iso_crosswalks/iso_30111_2019.md'
      - ISO 29147: 'reference/iso_crosswalks/iso_29147_2018.md'
      - ISO 5895: 'reference/iso_crosswalks/iso_5895_2022.md'
    - SSVC Crosswalk: 'reference/ssvc_crosswalk.md'
    - Decision Records:
      - ADR Index: 'adr/index.md'
      - Record decisions: 'adr/0000-record-architecture-decisions.md'
      - Use MADR: 'adr/0001-use-markdown-any-decision-records.md'
      - Use Behavior Trees: 'adr/0002-model-processes-with-behavior-trees.md'
      - Build a Behavior Tree library: 'adr/0003-build-custom-python-bt-engine.md'
      - Use Factory Pattern for BT nodes: 'adr/0004-use-factory-methods-for-common-bt-node-types.md'
      - Use ActivityStreams Vocabulary as Message Format: 'adr/0005-activitystreams-vocabulary-as-vultron-message-format.md'
  - About:
    - Contributing: 'about/contributing.md'
    - FAQ: 'about/faq.md'
    - Acknowledgements: 'about/acknowledgements.md'
    - License: 'about/license.md'
  - Issue Tracker: 'https://github.com/CERTCC/Vultron/issues'
not_in_nav: |
    includes/*
    topics/user_stories/story_*.md
    *diagram*.md
    *table*.md
    _*.md
theme:
  logo: 'assets/cert_seal.svg'
  name: 'material'
  features:
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.prune
    - navigation.indexes
    - search.highlight
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    scheme: 'cmu'
    accent: 'red'
  icon:
    repo: fontawesome/brands/github
plugins:
  - bibtex:
      bib_file: 'references.bib'
  - include-markdown:
      comments: false
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      handlers:
        python:
          paths: [ 'src' ]
          options:
            show_bases: true
            show_root_heading: true
            heading_level: 2
  - markdown-exec
  - search
  # NOTE print-site MUST be the last plugin in the list (see its docs for why)
  - print-site
repo_url: 'https://github.com/CERTCC/Vultron'
repo_name: 'CERTCC/Vultron'
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
extra:
  analytics:
    provider: google
    property: G-87WECW6HCS
  consent:
    title: About our use of cookies on this site
    description: >-
      We use cookies to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better. 
      See our <a href="https://www.sei.cmu.edu/legal/privacy-notice/index.cfm">Privacy Notice</a> for more.
  social:
    - icon: fontawesome/solid/bug
      link: https://github.com/CERTCC/Vultron/issues
      name: Report an Issue or Suggest a Change
    - icon: fontawesome/brands/github
      link: https://github.com/CERTCC/Vultron
      name: CERTCC/Vultron on Github
    - icon: fontawesome/regular/envelope
      link: mailto:cert@cert.org?subject=Vultron%20Protocol%20Feedback
      name: Email CERT/CC
    - icon: fontawesome/solid/house
      link: https://www.sei.cmu.edu/
      name: Software Engineering Institute
extra_javascript:
  # to render math
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # to sort tables
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
extra_css:
  - stylesheets/extra.css
